sudo: required

services:
  - docker

os:
- linux

env:
  global:
    - DOCKER_IMAGE_NAME="guestbook"
    - K8S_DEPLOYMENT_NAME="guestbook"

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_script:
- docker pull smesch/hugo
- docker pull smesch/html-proofer
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/hugo_root smesch/hugo hugo -s /hugo_root
- docker run -v ${TRAVIS_BUILD_DIR}/public:/public smesch/html-proofer htmlproofer /public --external_only --only-4xx

after_script:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  # Auth flow
  - bash auth-gcloud.sh
  # Deployment if master branch and !PR
  - bash deploy.sh
